//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FetchRewardsApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FetchRewardsApi.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation would result in payer having a negative balance..
        /// </summary>
        internal static string NegativeBalanceError {
            get {
                return ResourceManager.GetString("NegativeBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spending a negative number of points is not allowed..
        /// </summary>
        internal static string NegativeSpendPointsError {
            get {
                return ResourceManager.GetString("NegativeSpendPointsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required payer balance record either was not found or could not be created. Operation is canceled..
        /// </summary>
        internal static string NullPayerBalanceReturned {
            get {
                return ResourceManager.GetString("NullPayerBalanceReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required spent points record either was not found or could not be created. Operation is canceled..
        /// </summary>
        internal static string NullSpentPointsReturned {
            get {
                return ResourceManager.GetString("NullSpentPointsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service level error occurred executing the action {0}.
        /// </summary>
        internal static string ServiceFault {
            get {
                return ResourceManager.GetString("ServiceFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to spend more points than are available to allocate..
        /// </summary>
        internal static string SpendingMorePointsThanAvailableError {
            get {
                return ResourceManager.GetString("SpendingMorePointsThanAvailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation resulted in one or more payers having a negative balance..
        /// </summary>
        internal static string SpendPointsCommand_PayerBalanceBecameNegativeError {
            get {
                return ResourceManager.GetString("SpendPointsCommand_PayerBalanceBecameNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining points became negative..
        /// </summary>
        internal static string SpendPointsCommand_RemainingPointsBecameNegativeError {
            get {
                return ResourceManager.GetString("SpendPointsCommand_RemainingPointsBecameNegativeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction would corrupt data in action {0}.
        /// </summary>
        internal static string TitleOperationWouldCorruptData {
            get {
                return ResourceManager.GetString("TitleOperationWouldCorruptData", resourceCulture);
            }
        }
    }
}
